"""empty message

Revision ID: 72e048d865a0
Revises: 22493872e5f1
Create Date: 2019-05-26 23:32:23.202079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e048d865a0'
down_revision = '22493872e5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.create_unique_constraint(None, 'client', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
